_target_: torch.nn.Sequential
_args_:
  - _target_: torch.nn.Dropout
    p: 0.4
  - _target_: torch.nn.Dropout1d
    p: 0.1
  - _target_: torch.nn.Linear
    in_features: ${variables.mil_hidden_features}
    out_features: 1
  - _target_: torch.nn.Sigmoid    