# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
tcga_brca_images_root: ${oc.env:TCGA_BRCA_IMAGES_ROOT}
tcga_brca_images_glob: ${oc.env:TCGA_BRCA_IMAGES_GLOB}

clini_file: ${paths.root_dir}/data/clini/tcga_bc_tils.csv
mask_cache_dir: ${paths.log_dir}/preprocessing/masks


# path to logging directory
log_dir: ${oc.env:LOG_DIR}

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

h5_dump_dir: ${paths.output_dir}/features/tcga/bc/ffpe/retccl # Where to save the features relative to the versioned output dir
h5_root_dir: ${oc.env:TCGA_BRCA_H5_ROOT_DIR} # The root w/ versioning where it is saved after running the extraction


# path to working directory
work_dir: ${hydra:runtime.cwd}

# Statically set, since the files are already there.
datamodule_train_paths: ${paths.root_dir}/data/paths/train_fold_${variables.fold}.csv
datamodule_val_paths: ${paths.root_dir}/data/paths/val_fold_${variables.fold}.csv
datamodule_test_paths: ${paths.root_dir}/data/paths/test_fold_${variables.fold}.csv

