# @package _global_

defaults:
  - _self_
  - variables: default.yaml
  - datamodule: dlup_dataset.yaml
  - model: retccl_extractor.yaml
  - callbacks: none.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - extract_features: null
  - experiment: null
  - hparams_search: null
  - debug: null

task_name: "extract"
tags: ["extract"]
ckpt_path: null
seed: null
extract: True
