# @package _global_

defaults:
  - _self_
  - datamodule: h5.yaml
  - model: h5_regression.yaml
  - callbacks: default_regression.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - variables: default.yaml
  - experiment: null
  - hparams_search: null
  - optional local: default.yaml
  - debug: null

task_name: "train"
tags: ["train"]
train: True
test: True
ckpt_path: null
seed: null
